### ISSUE TITLE
FATAL EXCEPTION occurred when I clicked on the next button after denying access permission

### ISSUE THREAD

**Issue by sagorahmed** [n76/Symphony#20]
#### Expected behavior
I expected that I could click on every option after denying access permission.

#### Actual behavior
When I did deny access permission and tried to click on the track changer next button, then the app crashed.

#### How to reproduce
1. Install and open the app.
2. "DENY" when this app will ask your permission.
3. Then click on the "next" button (that button we usually use to change the song) and notice the error.

* App version: v1.1.10
* Operating system: Android 6.0.1

I know this issue sounds quite weird. Why would someone deny permission and click on that specific button?
But I am reporting it to you because I want this amazing app bug free from every possible way.

#### LogCat
```
04-30 09:06:34.422 26522 26522 E AndroidRuntime: FATAL EXCEPTION: main

04-30 09:06:34.422 26522 26522 E AndroidRuntime: Process: org.fitchfamily.android.symphony, PID: 26522

04-30 09:06:34.422 26522 26522 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater$a.onClick(Unknown Source)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at android.view.View.performClick(View.java:5714)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22589)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	... 10 more

04-30 09:06:34.422 26522 26522 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.fitchfamily.android.symphony.MusicService$b.a()' on a null object reference

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.k(Unknown Source)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.l(Unknown Source)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.skipForward(Unknown Source)

04-30 09:06:34.422 26522 26522 E AndroidRuntime: 	... 11 more
```

**Comment by n76** [comment]
Looks like it also fails if you tap the back button under the same conditions. :(

**Comment by sagorahmed** [comment]
Hello @n76 
No, the back button is working fine. I don't get any problem with that.
